language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t manijassar/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true manijassar/react-test npm test

after_success:
        - docker build -t manijassar/multi-client ./client
        - docker build -t manijassar/multi-nginx ./nginx
        - docker build -t manijassar/multi-server ./server
        - docker build -t manijassar/multi-worker ./worker
        # login and push images to docker hub
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push manijassar/multi-client
        - docker push manijassar/multi-nginx
        - docker push manijassar/multi-server
        - docker push manijassar/multi-worker





